"""Strategy library & strategic-variable definitions (architecture.md §17.4 / §17.5).

Structured knowledge — the rule-based matcher (sandbox.match_strategies) reads
suitable_conditions / avoid_conditions directly, so their keys MUST be names
from STRATEGIC_VARIABLES.
"""
from __future__ import annotations

# --- §17.5 strategic variables --------------------------------------------
# value scale: low / medium / high / unknown
STRATEGIC_VARIABLES: dict[str, str] = {
    "market_attractiveness": "市场吸引力",
    "competition_intensity": "竞争强度",
    "brand_awareness": "周大福品牌认知度",
    "cultural_fit": "东方黄金文化契合度",
    "channel_maturity": "高端渠道成熟度",
    "regulatory_risk": "合规风险",
    "trial_cost": "试错成本",
    "time_window": "时间窗口紧迫度",
    "localization_difficulty": "本地化难度",
    "strategic_reversibility": "战略可逆性（能否低成本撤退）",
    "chinese_community_base": "华人社群基础",
    "wedding_demand": "婚庆需求",
    "social_buzz_strength": "社媒声量强度",
    "pricing_pressure": "价格压力（金价高企）",
}
VARIABLE_VALUES = ["low", "medium", "high", "unknown"]

# --- §17.4 strategy library (12 strategies) -------------------------------
STRATEGY_LIBRARY: list[dict] = [
    {
        "strategy_id": "light_cavalry_test",
        "strategy_name": "轻骑探路",
        "classical_source": "暗度陈仓 / 先为不可胜",
        "business_meaning": "用快闪、店中店、限量产品等轻资产方式验证市场，避免一开始重资产投入。",
        "suitable_conditions": {
            "market_attractiveness": ["medium", "high"],
            "brand_awareness": ["low", "medium"],
            "trial_cost": ["low", "medium"],
            "strategic_reversibility": ["medium", "high"],
        },
        "avoid_conditions": {"regulatory_risk": ["high"]},
        "recommended_actions": ["快闪店测试", "店中店试水", "限量产品测试", "小范围私享会"],
        "expected_benefits": ["降低首次进入固定成本", "快速验证产品与价格带", "失败可低成本撤退"],
        "key_risks": ["品牌沉淀较弱", "短期销售贡献有限"],
        "validation_metrics": ["客流量", "试戴率", "询价率", "转化率", "客单价"],
        "example_use_case": "市场机会存在但品牌认知尚未验证的场景。",
    },
    {
        "strategy_id": "harbour_landing",
        "strategy_name": "借港登岸",
        "classical_source": "借船出海 / 借力打力",
        "business_meaning": "借成熟高端商场、百货、旅游零售渠道入场，不自建重渠道。",
        "suitable_conditions": {
            "channel_maturity": ["high"],
            "market_attractiveness": ["medium", "high"],
            "trial_cost": ["low", "medium"],
        },
        "avoid_conditions": {"localization_difficulty": ["high"]},
        "recommended_actions": ["进驻核心商场专柜", "机场 / 旅游零售点位", "高端百货店中店"],
        "expected_benefits": ["借现成客流与信任背书", "缩短渠道建设周期"],
        "key_risks": ["渠道议价权弱", "受商场政策与租金牵制"],
        "validation_metrics": ["专柜坪效", "客流转化率", "旅游客占比"],
        "example_use_case": "高端渠道成熟、但自建门店成本高的市场。",
    },
    {
        "strategy_id": "strike_the_void",
        "strategy_name": "避实击虚",
        "classical_source": "避实击虚",
        "business_meaning": "避开国际大牌强势的高珠红海，主攻被忽视的细分（轻量金、日常佩戴）。",
        "suitable_conditions": {
            "competition_intensity": ["high"],
            "pricing_pressure": ["high"],
            "social_buzz_strength": ["medium", "high"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["主推轻克重 / 固定价产品", "聚焦日常佩戴场景", "差异化设计款"],
        "expected_benefits": ["绕开大牌正面竞争", "贴合价格敏感消费者"],
        "key_risks": ["细分市场天花板有限", "易被快速跟进"],
        "validation_metrics": ["轻量款销售占比", "复购率", "新客占比"],
        "example_use_case": "国际大牌主导高珠、消费者转向高性价比的市场。",
    },
    {
        "strategy_id": "cultural_anchor",
        "strategy_name": "文化定锚",
        "classical_source": "以正合 / 师出有名",
        "business_meaning": "用东方黄金工艺与文化叙事建立差异化品牌心智。",
        "suitable_conditions": {
            "cultural_fit": ["medium", "high"],
            "chinese_community_base": ["medium", "high"],
            "brand_awareness": ["low", "medium"],
        },
        "avoid_conditions": {"cultural_fit": ["low"]},
        "recommended_actions": ["古法金 / 非遗工艺叙事", "文化联名", "工艺体验活动"],
        "expected_benefits": ["建立不可替代的品牌差异", "提升溢价能力"],
        "key_risks": ["文化叙事见效慢", "需持续内容投入"],
        "validation_metrics": ["品牌搜索量", "内容互动率", "工艺款溢价幅度"],
        "example_use_case": "存在东方文化共鸣、品牌仍需教育消费者的市场。",
    },
    {
        "strategy_id": "small_gold_lure",
        "strategy_name": "小金引玉",
        "classical_source": "抛砖引玉",
        "business_meaning": "用「保值黄金」做引流入口，带动设计款与镶嵌品类。",
        "suitable_conditions": {
            "pricing_pressure": ["high"],
            "market_attractiveness": ["medium", "high"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["金条 / 投资金引流", "黄金回收以旧换新", "引导转化设计款"],
        "expected_benefits": ["承接保值需求客流", "拉动高毛利品类"],
        "key_risks": ["引流客未必转化", "金条本身毛利低"],
        "validation_metrics": ["引流客转设计款比例", "连带率", "回收转购率"],
        "example_use_case": "金价高企、消费者强烈追求保值的市场。",
    },
    {
        "strategy_id": "chinese_circle_icebreaker",
        "strategy_name": "华圈破冰",
        "classical_source": "远交近攻",
        "business_meaning": "先打华人社群（婚庆、礼赠、节庆），以此为据点再向外扩。",
        "suitable_conditions": {
            "chinese_community_base": ["high"],
            "wedding_demand": ["medium", "high"],
            "cultural_fit": ["medium", "high"],
        },
        "avoid_conditions": {"chinese_community_base": ["low"]},
        "recommended_actions": ["华人社团 / 商会合作", "礼赠与节庆场景营销", "华人 KOL 种草"],
        "expected_benefits": ["快速找到高确定性客群", "口碑在社群内扩散快"],
        "key_risks": ["客群天花板", "易被贴上「只做华人」标签"],
        "validation_metrics": ["华人客占比", "社群活动转化", "口碑转介率"],
        "example_use_case": "华人社群规模大、礼赠婚庆需求明确的市场。",
    },
    {
        "strategy_id": "voice_before_store",
        "strategy_name": "先声后店",
        "classical_source": "先声夺人",
        "business_meaning": "先做社媒声量与内容种草，再落地实体门店。",
        "suitable_conditions": {
            "social_buzz_strength": ["medium", "high"],
            "brand_awareness": ["low", "medium"],
            "channel_maturity": ["low", "medium"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["社媒内容矩阵", "KOL / KOC 种草", "线上预热后再开店"],
        "expected_benefits": ["开店前已有声量", "降低首店冷启动风险"],
        "key_risks": ["声量未必转化到店", "内容投入需持续"],
        "validation_metrics": ["内容互动率", "搜索增长", "到店询问中线上来源占比"],
        "example_use_case": "社媒活跃、品牌认知低、渠道尚未铺开的市场。",
    },
    {
        "strategy_id": "highground_position",
        "strategy_name": "高地占位",
        "classical_source": "占据制高点 / 抢占先机",
        "business_meaning": "在核心商场、机场旗舰点位抢占高端心智，先发占位。",
        "suitable_conditions": {
            "market_attractiveness": ["high"],
            "competition_intensity": ["medium", "high"],
            "channel_maturity": ["high"],
            "time_window": ["medium", "high"],
        },
        "avoid_conditions": {"strategic_reversibility": ["low"], "market_attractiveness": ["low"]},
        "recommended_actions": ["核心商圈旗舰店", "机场高端点位", "标志性陈列与体验"],
        "expected_benefits": ["抢占高端心智", "形成竞品进入壁垒"],
        "key_risks": ["重资产、可逆性低", "回收周期长"],
        "validation_metrics": ["旗舰店品牌曝光", "高端客占比", "心智份额调研"],
        "example_use_case": "市场吸引力高、窗口期紧迫、需先发占位的市场。",
    },
    {
        "strategy_id": "wedding_alliance",
        "strategy_name": "婚庆结盟",
        "classical_source": "合纵连横",
        "business_meaning": "与婚庆、酒店、婚摄等生态结盟，锁定三金 / 对戒场景。",
        "suitable_conditions": {
            "wedding_demand": ["high"],
            "cultural_fit": ["medium", "high"],
            "chinese_community_base": ["medium", "high"],
        },
        "avoid_conditions": {"wedding_demand": ["low"]},
        "recommended_actions": ["婚庆生态异业结盟", "三金 / 对戒套系", "婚展与酒店合作"],
        "expected_benefits": ["锁定高客单刚需场景", "结盟方互相导流"],
        "key_risks": ["依赖结盟方质量", "婚庆需求有季节性"],
        "validation_metrics": ["婚庆套系销售额", "结盟渠道转化", "对戒客单价"],
        "example_use_case": "婚庆需求旺盛、华人婚俗讲究三金的市场。",
    },
    {
        "strategy_id": "reversible_advance",
        "strategy_name": "可退可进",
        "classical_source": "以退为进",
        "business_meaning": "用可快速撤退的形态（快闪、租柜、联营）进入高不确定市场。",
        "suitable_conditions": {
            "regulatory_risk": ["medium", "high"],
            "localization_difficulty": ["medium", "high"],
            "strategic_reversibility": ["high"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["短租点位", "联营 / 代销模式", "可快速撤店的轻形态"],
        "expected_benefits": ["在高不确定下保留退路", "边走边看降低损失"],
        "key_risks": ["难以建立长期品牌资产", "团队投入不稳定"],
        "validation_metrics": ["单点位回本周期", "撤退成本", "试点转正率"],
        "example_use_case": "合规复杂、本地化难、不确定性高的市场。",
    },
    {
        "strategy_id": "gold_over_diamond",
        "strategy_name": "避钻攻金",
        "classical_source": "避实击虚",
        "business_meaning": "在钻饰被国际大牌主导时，集中黄金品类（文化 + 保值双属性）。",
        "suitable_conditions": {
            "pricing_pressure": ["high"],
            "competition_intensity": ["high"],
            "cultural_fit": ["medium", "high"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["集中黄金品类资源", "强化黄金保值 + 文化叙事", "弱化与大牌钻饰正面比"],
        "expected_benefits": ["发挥黄金主场优势", "规避钻饰红海"],
        "key_risks": ["放弃钻饰高端形象", "金价波动直接影响"],
        "validation_metrics": ["黄金品类占比", "黄金客单价", "毛利结构"],
        "example_use_case": "钻饰被国际大牌占据、黄金有文化与保值需求的市场。",
    },
    {
        "strategy_id": "festival_spike",
        "strategy_name": "节庆爆点",
        "classical_source": "因势利导 / 趁势而起",
        "business_meaning": "围绕春节、婚季、节庆做爆点投放与限定产品。",
        "suitable_conditions": {
            "wedding_demand": ["medium", "high"],
            "social_buzz_strength": ["medium", "high"],
            "time_window": ["medium", "high"],
        },
        "avoid_conditions": {},
        "recommended_actions": ["节庆限定系列", "节点集中投放", "节庆礼赠场景内容"],
        "expected_benefits": ["在高需求节点集中收割", "限定款带动话题"],
        "key_risks": ["节点过后回落", "需提前备货"],
        "validation_metrics": ["节庆期销售峰值", "限定款售罄率", "节庆内容互动"],
        "example_use_case": "存在明确节庆 / 婚季节点、社媒易引爆的市场。",
    },
]

STRATEGY_BY_ID = {s["strategy_id"]: s for s in STRATEGY_LIBRARY}

# --- §17.8 ranking weights (rule config; LLM scores each dimension) -------
# risk_exposure / investment_cost / execution_difficulty are NEGATIVE.
RANKING_WEIGHTS: dict[str, float] = {
    "opportunity_gain": 0.22,
    "risk_exposure": -0.18,
    "investment_cost": -0.13,
    "execution_difficulty": -0.12,
    "validation_speed": 0.15,
    "strategic_reversibility": 0.10,
    "long_term_brand_value": 0.10,
}
